"""status

Revision ID: 173359a4a188
Revises: 97994d88d747
Create Date: 2022-04-16 22:07:36.316526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '173359a4a188'
down_revision = '97994d88d747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_check', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_check', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
