"""empty message

Revision ID: 4194a3840af8
Revises: 173359a4a188
Create Date: 2022-04-20 22:33:45.838461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4194a3840af8'
down_revision = '173359a4a188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('rating')

    with op.batch_alter_table('my_courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_courses', schema=None) as batch_op:
        batch_op.drop_column('liked')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
