"""images

Revision ID: 5b3c777a6fbb
Revises: 8c2e3fb20649
Create Date: 2022-02-27 18:29:31.573698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3c777a6fbb'
down_revision = '8c2e3fb20649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_path', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('img_uuid', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_img_uuid'), ['img_uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_img_uuid'))
        batch_op.drop_column('img_uuid')
        batch_op.drop_column('img_path')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
