"""empty message

Revision ID: 8c2e3fb20649
Revises: 88620a022b18
Create Date: 2022-02-27 15:41:46.609965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2e3fb20649'
down_revision = '88620a022b18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=64), nullable=True),
    sa.Column('uuid', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_file_name'), 'lesson_file', ['name'], unique=False)
    op.create_index(op.f('ix_lesson_file_uuid'), 'lesson_file', ['uuid'], unique=False)
    op.drop_index('ix_page_file_name', table_name='page_file')
    op.drop_index('ix_page_file_uuid', table_name='page_file')
    op.drop_table('page_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_file',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('path', sa.VARCHAR(length=64), nullable=True),
    sa.Column('uuid', sa.VARCHAR(length=64), nullable=True),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('page_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_page_file_uuid', 'page_file', ['uuid'], unique=False)
    op.create_index('ix_page_file_name', 'page_file', ['name'], unique=False)
    op.drop_index(op.f('ix_lesson_file_uuid'), table_name='lesson_file')
    op.drop_index(op.f('ix_lesson_file_name'), table_name='lesson_file')
    op.drop_table('lesson_file')
    # ### end Alembic commands ###
