"""empty message

Revision ID: 97994d88d747
Revises: 5375a2e3238c
Create Date: 2022-04-16 21:40:38.689228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97994d88d747'
down_revision = '5375a2e3238c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_check', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_index', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_check', schema=None) as batch_op:
        batch_op.drop_column('page_index')

    # ### end Alembic commands ###
